#!/usr/bin/env bash
# Provision truffe-eu cloud Supabase + push to Vercel.
# Prerequisites: `supabase login` and SUPABASE_DB_PASSWORD in env.
#
# Usage:
#   SUPABASE_DB_PASSWORD='...' ./scripts/supabase-eu-provision.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

REF="${SUPABASE_PROJECT_REF:-ltoqmvaiolyqyfykkxxs}"
HOST="aws-0-eu-central-1.pooler.supabase.com"
URL="https://${REF}.supabase.co"

if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]] && [[ -f "$ROOT/.env" ]]; then
  SUPABASE_DB_PASSWORD="$(grep -E '^SUPABASE_DB_PASSWORD=' "$ROOT/.env" | head -1 | cut -d= -f2- | tr -d "'\"")"
fi

if [[ -z "${SUPABASE_DB_PASSWORD:-}" ]]; then
  echo "Set SUPABASE_DB_PASSWORD (from Supabase project creation)." >&2
  exit 1
fi

echo "→ Fetching API keys for ${REF}..."
KEYS_JSON="$(supabase projects api-keys --project-ref "$REF" --reveal --output json)"
ANON_KEY="$(printf '%s' "$KEYS_JSON" | node -e "
const keys = JSON.parse(require('fs').readFileSync(0, 'utf8'));
console.log(keys.find((k) => k.name === 'anon')?.api_key ?? '');
")"
SERVICE_KEY="$(printf '%s' "$KEYS_JSON" | node -e "
const keys = JSON.parse(require('fs').readFileSync(0, 'utf8'));
console.log(keys.find((k) => k.name === 'service_role')?.api_key ?? '');
")"

if [[ -z "$ANON_KEY" || -z "$SERVICE_KEY" ]]; then
  echo "Could not parse API keys. Run: supabase login" >&2
  exit 1
fi

# URL-encode password for connection strings
ENC_PASS="$(node -e "console.log(encodeURIComponent(process.argv[1]))" "$SUPABASE_DB_PASSWORD")"
DIRECT_URL="postgresql://postgres.${REF}:${ENC_PASS}@${HOST}:5432/postgres"
POOL_URL="postgresql://postgres.${REF}:${ENC_PASS}@${HOST}:6543/postgres?pgbouncer=true"

echo "→ Linking Supabase project..."
supabase link --project-ref "$REF" --password "$SUPABASE_DB_PASSWORD" --yes

echo "→ Writing cloud vars to .env.production (local only, gitignored)..."
{
  cat <<EOF
# truffe-eu cloud — generated by scripts/supabase-eu-provision.sh
SUPABASE_URL=${URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}
SUPABASE_DB_DIRECT_URL=${DIRECT_URL}
SUPABASE_DB_URL=${POOL_URL}
DATABASE_URL=${POOL_URL}
RP_ID=truffe.vercel.app
RP_NAME=truffe.ai
ORIGIN=https://truffe.vercel.app
SESSION_COOKIE_NAME=__Host-session
EOF
  # Carry over app secrets from local .env (never commit)
  if [[ -f "$ROOT/.env" ]]; then
    grep -E '^(ADMIN_EMAIL|ANTHROPIC_API_KEY|MODEL_ADVISOR|CRON_SECRET|RP_NAME)=' "$ROOT/.env" || true
  fi
} > "$ROOT/.env.production"

echo "→ Applying Drizzle migrations..."
pnpm exec dotenv -e .env.production -- pnpm exec drizzle-kit migrate

echo "→ Deploying jwt-claims edge function..."
supabase functions deploy jwt-claims --no-verify-jwt --project-ref "$REF"

echo "→ Pushing env to Vercel..."
ENV_FILE="$ROOT/.env.production" "$ROOT/scripts/vercel-env-push.sh" --force

echo ""
echo "Manual dashboard steps (one-time):"
echo "  1. Auth → Hooks → Custom Access Token Hook → jwt-claims"
echo "  2. Auth → URL Configuration → add https://truffe.vercel.app/auth/callback"
echo "  3. Auth → Providers → Passkeys → enable (rp_id truffe.vercel.app for now)"
echo ""
echo "→ Redeploying Vercel production..."
pnpm dlx vercel deploy --prod --yes

echo "Done. Smoke: https://truffe.vercel.app/api/health"
